"""create table deteksi

Revision ID: d883bbc04686
Revises: 
Create Date: 2025-06-03 12:04:20.788940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd883bbc04686'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deteksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tekanan_darah', sa.Float(), nullable=False),
    sa.Column('kolesterol', sa.Float(), nullable=False),
    sa.Column('gula_darah', sa.Float(), nullable=False),
    sa.Column('risiko', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pendeteksi')
    op.drop_table('doctors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('specialty', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('whatsapp_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='doctors_pkey')
    )
    op.create_table('pendeteksi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tekanan_darah', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kolesterol', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gula_darah', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('risiko_penyakit_jantung', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pendeteksi_pkey')
    )
    op.drop_table('deteksi')
    # ### end Alembic commands ###
